server:
  port: 8085

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password

properties:
  externalUrl:
    session: http://lna-session-api:8080/api/session
    integrationAI: http://lna-ai-integration-api:8080/api/openai