server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

properties:
  externalUrl:
    session: http://localhost:8080/api/session
    integrationAI: http://localhost:8081/api/openai